version: "3.1"
services:
  app-1:
    build:
      context: "./app-1"
    ports:
      - "8080:8080"
    volumes:
      - "./app-1:/opt/app"
      - "/opt/app/node_modules"
    depends_on:
      - "app-2"
    command: "run dev"
  app-2:
    build:
      context: "./app-2"
    volumes:
      - "./app-2:/opt/app"
      - "/opt/app/node_modules"
    command: "run dev"
